// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkg4-CTNwNHb6dUJRgmTGH1Uo0d4-wrQ',
    appId: '1:435527852074:web:d44960a52a36d0da40a353',
    messagingSenderId: '435527852074',
    projectId: 'petverse-14e34',
    authDomain: 'petverse-14e34.firebaseapp.com',
    storageBucket: 'petverse-14e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj7OsV_JQ0RJYRkCevowsbZTXriK-kUU0',
    appId: '1:435527852074:android:af31268ac8fe5c4940a353',
    messagingSenderId: '435527852074',
    projectId: 'petverse-14e34',
    storageBucket: 'petverse-14e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwf_ME-udMlBq1_3Nkd4AUJrhVpsJQI8',
    appId: '1:435527852074:ios:fccd16555a60b4da40a353',
    messagingSenderId: '435527852074',
    projectId: 'petverse-14e34',
    storageBucket: 'petverse-14e34.firebasestorage.app',
    iosBundleId: 'com.example.petverseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwf_ME-udMlBq1_3Nkd4AUJrhVpsJQI8',
    appId: '1:435527852074:ios:fccd16555a60b4da40a353',
    messagingSenderId: '435527852074',
    projectId: 'petverse-14e34',
    storageBucket: 'petverse-14e34.firebasestorage.app',
    iosBundleId: 'com.example.petverseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqkg4-CTNwNHb6dUJRgmTGH1Uo0d4-wrQ',
    appId: '1:435527852074:web:8decf7e7b8e1deec40a353',
    messagingSenderId: '435527852074',
    projectId: 'petverse-14e34',
    authDomain: 'petverse-14e34.firebaseapp.com',
    storageBucket: 'petverse-14e34.firebasestorage.app',
  );
}
